language: go
go: 1.19
script: 
  - go mod init github.com/ilya1st/configuration-go
  - go mod tidy
  - go get -u 
  - go test -race
sudo: false
notifications:
  email:
    on_success: never
    on_failure: never